# Generated by Django 5.1.4 on 2026-04-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackBoxIncident',
            fields=[
                ('incident_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('opened_at', models.CharField(max_length=32)),
                ('closed_at', models.CharField(blank=True, max_length=32, null=True)),
                ('code', models.CharField(max_length=16)),
                ('machine_id', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=16)),
                ('first_drift_ts', models.CharField(blank=True, max_length=32, null=True)),
                ('detected_ts', models.CharField(max_length=32)),
                ('status', models.CharField(default='open', max_length=16)),
                ('assigned_tech', models.CharField(blank=True, max_length=32, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'black_box_incidents',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='BlackBoxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=32)),
                ('phase', models.CharField(max_length=32)),
                ('agent', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=128)),
                ('inputs_json', models.TextField()),
                ('outputs_json', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField()),
                ('status', models.CharField(max_length=16)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.blackboxincident')),
            ],
            options={
                'db_table': 'black_box_log',
                'ordering': ['id'],
            },
        ),
    ]
